[package]
name = "try_stm32l4"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
nb = "1.1.0"
panic-halt = "1.0.0"
rtt-target = "0.6.1"

stm32l4xx-hal = { version = "0.7.1", features = ["rt", "stm32l4a6"] }
